os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.7"
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
addons:
  firefox: 77.0
  apt:
    packages:
      firefox-geckodriver
env:
  jobs:
    - PLONE_VERSION=5.2.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - pip install -r requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - buildout -t 10 -c travis.cfg
script:
#  - make code-analysis
#  - make test-release
  - make test